'use strict';
const {_electron:electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),workspace=root,profile=path.join(workspace,'tmp/flow-profile'),out=path.join(workspace,'tmp/qa-flows');
fs.mkdirSync(out,{recursive:true});fs.rmSync(profile,{recursive:true,force:true});
const config={executablePath:process.env.ELECTRON_PATH||require('electron'),args:['--no-sandbox','--disable-gpu',process.env.APP_PATH||path.join(workspace,'app'),'--user-data-dir='+profile],env:{...process.env,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'}};
let app,page;const errors=[],checks=[];
const action=name=>page.locator(`[data-action="${name}"]`).first();
async function nav(name){await page.locator(`.nav [data-view="${name}"]`).click();await page.waitForSelector('h1')}
async function field(key,value){const locator=page.locator(`[data-field="${key}"]`);await locator.fill(String(value));await locator.press('Tab')}
async function trait(group,key,value){const locator=page.locator(`[data-trait="${group}"][data-key="${key}"]`);await locator.fill(String(value));await locator.press('Tab');assert.equal(await page.evaluate(([g,k])=>ch()[g][k],[group,key]),value)}
async function option(list,name,value,{granted=false,inClan=false,notes=''}={}){await page.locator(`[data-action="new-option"][data-list="${list}"]`).click();await page.locator('#option-name').fill(name);await page.locator('#option-value').fill(String(value));if(await page.locator('#option-in-clan').count())await page.locator('#option-in-clan').setChecked(inClan);if(await page.locator('#option-granted').count())await page.locator('#option-granted').setChecked(granted);await page.locator('#option-notes').fill(notes);await action('save-option').click();await page.waitForFunction(()=>!document.querySelector('#modal').open)}
function check(name){checks.push(name);console.log('PASS '+name)}
async function launch(){app=await electron.launch(config);app.on('window',p=>p.on('pageerror',e=>errors.push(e.message)));page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('h1');assert.equal(await page.evaluate(()=>storageBlocked),false)}
async function addCatalog(category,query=''){await nav('catalogo');await page.locator('#catalog-category').selectOption(category);await page.locator('#catalog-book').selectOption('');await page.locator('#catalog-search').fill(query);await page.waitForTimeout(250);await page.evaluate(()=>waitForSearch());await page.waitForFunction(category=>!searchStates.catalog.result.pending&&searchStates.catalog.result.rows.some(e=>e.category===category),category);const entry=await page.evaluate(category=>searchStates.catalog.result.rows.find(e=>e.category===category),category);await page.locator(`[data-action="add-entry"][data-id="${entry.id}"]`).click();return entry}
async function nativeSave(file){fs.rmSync(path.join(out,file),{force:true});await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},path.join(out,file))}
async function waitFile(file){const destination=path.join(out,file);for(let i=0;i<120;i++){if(fs.existsSync(destination)&&fs.statSync(destination).size>100)return destination;await page.waitForTimeout(100)}throw Error('Arquivo não criado: '+destination+'; mensagem da interface: '+await page.locator('#toast').textContent())}
(async()=>{try{
 await launch();assert.equal(await page.evaluate(()=>ch().generation),12);check('primeira inicialização limpa, padrão DAV20 e ponte nativa');
 await nav('personagem');await field('name','Luciana de Valois');await field('player','Teste de integração');await field('chronicle','Paris — 1242');await field('concept','Senescal e guardiã de manuscritos');await field('history','Escriba mortal, abraçada numa corte em crise.');await field('notes','Uma dívida antiga com o senhor da cidade.');await field('bloodPreference','Clérigos que preservam seus votos');await page.locator('[data-field="clan"]').selectOption('Ventrue');assert.ok((await page.evaluate(()=>ch().weakness)).includes('tipo específico de mortal'));await field('weakness','Só recebe sustento de clérigos que preservam seus votos; exceção aprovada na crônica.');assert.ok((await page.evaluate(()=>ch().weakness)).includes('exceção aprovada'));await page.locator('[data-field="road"]').selectOption('Road of Sin');assert.deepEqual(await page.evaluate(()=>ch().virtueTypes),{moral:'conviction',restraint:'instinct'});assert.deepEqual(await page.evaluate(()=>ch().virtues),{moral:1,restraint:1,courage:1});await page.locator('[data-field="road"]').selectOption('Road of Humanity');assert.equal(await page.evaluate(()=>ch().virtueTypes.moral),'conscience');check('identidade, clã, restrição de sangue e mudança de Caminho com Virtudes corretas');
 await nav('atributos');await page.locator('[data-priority="attribute"][data-group="physical"]').selectOption('1');assert.deepEqual(await page.evaluate(()=>ch().creation.attributePriorities),['social','physical','mental']);await page.locator('[data-priority="attribute"][data-group="physical"]').selectOption('0');
 const attrs={strength:4,dexterity:3,stamina:3,charisma:3,manipulation:3,appearance:2,perception:2,intelligence:2,wits:2};for(const [key,value]of Object.entries(attrs))await trait('attributes',key,value);await page.locator('[data-specialty="strength"]').fill('Erguer portões');
 await nav('habilidades');await page.locator('[data-priority="ability"][data-group="skills"]').selectOption('0');assert.deepEqual(await page.evaluate(()=>ch().creation.abilityPriorities),['skills','talents','knowledges']);await page.locator('[data-priority="ability"][data-group="talents"]').selectOption('0');const abilities={alertness:3,athletics:3,awareness:3,brawl:3,empathy:1,animalKen:3,archery:3,commerce:3,academics:3,enigmas:2};for(const [key,value]of Object.entries(abilities))await trait('abilities',key,value);check('prioridades trocam sem duplicar categorias e distribuição 7/5/3, 13/9/5');
 await nav('vantagens');for(const [name,rating]of [['Dominate',2],['Fortitude',1],['Presence',1]])await option('disciplines',name,rating,{inClan:true});await option('backgrounds','Mentor',3);await option('backgrounds','Contacts',2);for(const [key,value]of Object.entries({moral:3,restraint:4,courage:3}))await trait('virtues',key,value);assert.deepEqual(await page.evaluate(()=>stats().warnings),[]);assert.equal(await page.evaluate(()=>stats().roadScore),7);assert.equal(await page.evaluate(()=>stats().willpowerMax),3);
 await nav('criacao');await action('freeze-creation').click();await action('confirm-freeze').click();assert.equal(await page.evaluate(()=>ch().creation.phase),'freebies');assert.equal(await page.evaluate(()=>ch().creation.base.attributes.strength),4);check('distribuição completa sem avisos e registro da base inicial');
 await nav('atributos');await trait('attributes','strength',5);await nav('vantagens');await field('willpower',5);await option('merits','Qualidade de teste',3);await option('flaws','Defeito de teste',2);await option('rituals','Ritual concedido de teste',1,{granted:true,notes:'Concessão da disciplina, sem custo adicional.'});await option('paths','Trilha secundária de teste',1,{notes:'Trilha comprada com quatro pontos de bônus.'});assert.equal(await page.evaluate(()=>stats().freebieSpent),14);assert.equal(await page.evaluate(()=>stats().freebieAvailable),17);assert.equal(await page.evaluate(()=>ch().rituals.length),1);assert.equal(await page.evaluate(()=>ch().paths.length),1);assert.equal(await page.evaluate(()=>ch().creation.base.attributes.strength),4);check('bônus separados da base, qualidades/defeitos e rituais concedidos em lista própria');
 await nav('criacao');await action('enter-play').click();await action('confirm-play').click();await page.locator('#xp-amount').fill('30');await action('gain-xp').click();await action('buy-xp').click();await page.locator('#xp-type').selectOption('ability');await page.locator('#xp-key').selectOption('brawl');await page.locator('#xp-story').fill('Paris — história 1');await page.locator('#xp-notes').fill('Treino com os guardas da corte');await action('confirm-xp').click();assert.equal(await page.evaluate(()=>ch().abilities.brawl),4);assert.equal(await page.evaluate(()=>ch().experience.spent),6);assert.equal(await page.evaluate(()=>ch().experience.ledger[0].story),'Paris — história 1');assert.equal(await page.evaluate(()=>stats().freebieSpent),14);assert.equal(await page.evaluate(()=>stats().xpAvailable),24);check('compra com experiência registra custo e história sem cobrar bônus novamente');
 await nav('inventario');await action('new-equipment').click();await page.locator('#eq-name').fill('Cota de malha da corte');await page.locator('#eq-type').selectOption('armor');await page.locator('#eq-weight').fill('10.5');await page.locator('#eq-armor').fill('3');await page.locator('#eq-penalty').fill('1');await page.locator('#eq-equipped').check();await page.locator('#eq-notes').fill('Proteção física; não protege do sol.');await action('save-equipment').click();assert.equal(await page.evaluate(()=>ch().inventory[0].weight),10.5);assert.equal(await page.evaluate(()=>stats().attributes.dexterity),2);assert.equal(await page.evaluate(()=>stats().soak.lethal),7);check('equipamento com peso decimal aplica armadura, Destreza e absorção');
 await nav('sessao');await page.locator('#blood-current').fill('11');await page.locator('#blood-current').press('Tab');await page.locator('#wp-current').fill('5');await page.locator('#wp-current').press('Tab');await page.locator('#damage-type').selectOption('bashing');await page.locator('#damage-amount').fill('5');await action('apply-damage').click();assert.equal(await page.evaluate(()=>ch().health.bashing),2);assert.equal(await page.evaluate(()=>stats().healthPenalty),-1);await action('heal').click();assert.equal(await page.evaluate(()=>ch().health.bashing),1);assert.equal(await page.evaluate(()=>ch().resources.blood),10);await page.locator('#damage-type').selectOption('aggravated');await page.locator('#damage-amount').fill('1');await action('apply-damage').click();await page.locator('#heal-rested').check();await action('heal').click();assert.equal(await page.evaluate(()=>ch().health.aggravated),0);assert.equal(await page.evaluate(()=>ch().resources.blood),5);check('dano após absorção, divisão de contundente, cura e custo de agravado');
 await page.locator('#roll-pool').fill('5');await page.locator('#roll-difficulty').fill('8');await page.locator('#roll-purpose').fill('Teste determinístico de especialidade');await page.locator('#roll-specialty').check();await page.locator('#roll-willpower').check();await page.evaluate(()=>{window.savedRandom=Math.random;let i=0;const values=[2,3,8,10,10];Math.random=()=>((values[i++]??5)-.5)/10});await action('roll').click();await page.evaluate(()=>Math.random=window.savedRandom);assert.equal(await page.evaluate(()=>ch().rolls.at(-1).successes),6);assert.equal(await page.evaluate(()=>ch().resources.willpower),4);assert.deepEqual(await page.evaluate(()=>ch().rolls.at(-1).dice),[2,3,8,10,10]);assert.ok((await page.locator('#last-roll').innerText()).includes('6 sucesso'));assert.ok((await page.locator('.journal').first().innerText()).includes('Teste determinístico'));await page.locator('#journal-text').fill('Firmamos um pacto sob as torres de Paris.');await action('journal').click();assert.equal(await page.evaluate(()=>ch().journal.at(-1).text),'Firmamos um pacto sob as torres de Paris.');check('rolagem DAV20 com 10 duplo e vontade garantida, registro persistente e diário');
 const beforePaths=await page.evaluate(()=>ch().paths.length),beforeFreebies=await page.evaluate(()=>stats().freebieSpent);const natureEntry=await addCatalog('archetype','Defender');assert.ok(await page.locator('[data-action="use-nature"]').isVisible());assert.ok(await page.locator('[data-action="use-demeanor"]').isVisible());await action('use-nature').click();assert.equal(await page.evaluate(()=>ch().nature),natureEntry.label||natureEntry.name);const demeanorEntry=await addCatalog('archetype','Architect');await action('use-demeanor').click();assert.equal(await page.evaluate(()=>ch().demeanor),demeanorEntry.label||demeanorEntry.name);assert.equal(await page.evaluate(()=>ch().paths.length),beforePaths);assert.equal(await page.evaluate(()=>stats().freebieSpent),beforeFreebies);check('arquétipos do catálogo escolhem Natureza/Comportamento sem criar trilha ou custo');
 const beforeJournal=await page.evaluate(()=>ch().journal.length);const ruleEntry=await addCatalog('rule','Ancestral Nobre');await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.ok((await page.evaluate(()=>ch().journal.at(-1).text)).startsWith(ruleEntry.name));const settingEntry=await addCatalog('setting','O Domínio de Roma');await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.ok((await page.evaluate(()=>ch().journal.at(-1).text)).startsWith(settingEntry.name));assert.equal(await page.evaluate(()=>ch().journal.length),beforeJournal+2);assert.equal(await page.evaluate(()=>ch().paths.length),beforePaths);assert.equal(await page.evaluate(()=>stats().freebieSpent),beforeFreebies);check('referências de regras e cenário vão para o diário sem custo de trilha');
 await nav('modificadores');await action('new-bonus').click();await page.locator('#bonus-name').fill('Poder excepcional autorizado');await page.locator('#bonus-target').selectOption('attribute:strength');await page.locator('#bonus-value').fill('20000');await page.locator('#bonus-notes').fill('Valor grande preservado, sem limite artificial.');await action('save-bonus').click();assert.equal(await page.evaluate(()=>stats().attributes.strength),20005);await action('new-bonus').click();await page.locator('#bonus-name').fill('Proteção por dois turnos');await page.locator('#bonus-target').selectOption('dice');await page.locator('#bonus-value').fill('2');await page.locator('#bonus-duration').selectOption('turns');await page.locator('#bonus-remaining').fill('2');await action('save-bonus').click();await nav('sessao');await action('next-turn').click();assert.equal(await page.evaluate(()=>ch().bonuses[1].remaining),1);await action('next-turn').click();assert.equal(await page.evaluate(()=>ch().bonuses[1].enabled),false);assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);check('modificador +20000 sem cortes e efeito temporário expira no prazo');
 await nav('modificadores');for(const [target,value]of [['bloodMax',2],['bloodPerTurn',1],['traitMax',1]]){await action('new-bonus').click();await page.locator('#bonus-name').fill('Limite de crônica: '+target);await page.locator('#bonus-target').selectOption(target);await page.locator('#bonus-value').fill(String(value));await action('save-bonus').click()}assert.equal(await page.evaluate(()=>stats().bloodMax),13);assert.equal(await page.evaluate(()=>stats().bloodPerTurn),2);assert.equal(await page.evaluate(()=>stats().traitMax),6);check('editor aplica modificadores aos três limites de campanha');
 await nativeSave('luciana.dav20.json');await action('export').click();const exportedPath=await waitFile('luciana.dav20.json'),exported=JSON.parse(fs.readFileSync(exportedPath,'utf8'));assert.equal(exported.format,'vampire-dark-ages-v20');assert.equal(exported.characters[0].bonuses[0].value,20000);assert.equal(exported.characters[0].rituals.length,1);assert.equal(exported.characters[0].inventory[0].weight,10.5);assert.ok(exported.characters[0].weakness.includes('exceção aprovada'));assert.equal(exported.characters[0].nature,natureEntry.label||natureEntry.name);assert.equal(exported.characters[0].demeanor,demeanorEntry.label||demeanorEntry.name);assert.equal(exported.characters[0].journal.length,beforeJournal+2);assert.deepEqual(exported.characters[0].bonuses.slice(2).map(b=>b.target),['bloodMax','bloodPerTurn','traitMax']);
 await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},exportedPath);await action('import').click();await page.waitForFunction(()=>state.characters.length===2);assert.notEqual(await page.evaluate(()=>state.characters[0].id),await page.evaluate(()=>state.characters[1].id));assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);assert.equal(await page.evaluate(()=>stats().freebieSpent),14);assert.equal(await page.evaluate(()=>ch().experience.ledger.length),1);assert.ok((await page.evaluate(()=>ch().weakness)).includes('exceção aprovada'));assert.equal(await page.evaluate(()=>ch().nature),natureEntry.label||natureEntry.name);assert.equal(await page.evaluate(()=>ch().demeanor),demeanorEntry.label||demeanorEntry.name);assert.equal(await page.evaluate(()=>ch().journal.length),beforeJournal+2);assert.equal(await page.evaluate(()=>stats().bloodMax),13);assert.equal(await page.evaluate(()=>stats().bloodPerTurn),2);assert.equal(await page.evaluate(()=>stats().traitMax),6);check('exportação/importação nativa preserva números, rituais, base e compras de experiência');
 await nav('catalogo');await page.locator('#catalog-category').selectOption('');await page.locator('#catalog-search').fill('Fortitude');await page.waitForTimeout(250);await page.evaluate(()=>waitForSearch());await page.waitForFunction(()=>searchStates.catalog.result.total>0&&!searchStates.catalog.result.pending);assert.ok(await page.locator('[data-action="entry"]').count());await action('entry').click();assert.ok((await page.locator('.entry-text').innerText()).length>30);await action('close').click();await page.screenshot({path:path.join(out,'catalogo.png'),fullPage:true});
 await nav('biblioteca');await page.locator('#library-search').fill('Celerity');await page.waitForTimeout(250);await page.evaluate(()=>waitForSearch());await page.waitForFunction(()=>searchStates.library.result.total>0&&!searchStates.library.result.pending);await action('read-page').click();assert.ok((await page.locator('.page-text').innerText()).length>100);await action('close').click();const opened=app.waitForEvent('window');await action('source').click();const pdf=await opened;await pdf.waitForLoadState('domcontentloaded');assert.ok(pdf.url().includes('.pdf'));await pdf.close();check('catálogo e pesquisa da biblioteca, leitura textual e PDF original em janela nativa');
 await nav('resumo');await nativeSave('ficha-completa.pdf');await action('pdf').click();const complete=await waitFile('ficha-completa.pdf');assert.equal(fs.readFileSync(complete).subarray(0,5).toString(),'%PDF-');assert.ok(fs.statSync(complete).size>20000);
 await nav('biblioteca');assert.equal(await page.evaluate(()=>typeof window.desktop.official),'function');await nativeSave('ficha-oficial.pdf');await action('official-pdf').click();if(await page.locator('[data-action="confirm-official"]').count())await action('confirm-official').click();const official=await waitFile('ficha-oficial.pdf');assert.equal(fs.readFileSync(official).subarray(0,5).toString(),'%PDF-');assert.ok(fs.statSync(official).size>50000);check('PDF completo e ficha oficial preenchida por diálogos nativos');
 await nav('personagem');const before=await page.evaluate(()=>ch().notes);await field('notes','Persistência e desfazer ao fechar imediatamente.');await action('undo').click();assert.equal(await page.evaluate(()=>ch().notes),before);assert.ok(await page.evaluate(()=>journal.redo.length>0));await page.evaluate(()=>flushSave());await app.close();app=null;
 await launch();assert.equal(await page.evaluate(()=>state.characters.length),2);assert.equal(await page.evaluate(()=>ch().notes),before);assert.ok(await page.evaluate(()=>journal.redo.length>0));await action('redo').click();assert.equal(await page.evaluate(()=>ch().notes),'Persistência e desfazer ao fechar imediatamente.');assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);assert.equal(await page.evaluate(()=>ch().inventory[0].weight),10.5);assert.equal(await page.evaluate(()=>stats().freebieSpent),14);assert.equal(await page.evaluate(()=>ch().abilities.brawl),4);assert.equal(await page.evaluate(()=>ch().health.bashing),1);assert.ok((await page.evaluate(()=>ch().weakness)).includes('exceção aprovada'));assert.equal(await page.evaluate(()=>ch().nature),natureEntry.label||natureEntry.name);assert.equal(await page.evaluate(()=>ch().journal.length),beforeJournal+2);assert.equal(await page.evaluate(()=>stats().bloodMax),13);check('persistência ao fechar, identificadores e histórico com refazer após reiniciar');
 await nav('resumo');await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'visao-geral.png'),fullPage:true});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(960,720));await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'compacto.png'),fullPage:true});check('janela compacta sem rolagem horizontal e capturas para conferência visual');
 assert.deepEqual(errors,[]);await page.evaluate(()=>flushSave());await app.close();app=null;console.log(JSON.stringify({result:'PASS',checks:checks.length,errors,output:out},null,2));
}catch(error){if(page)try{await page.screenshot({path:path.join(out,'falha.png'),fullPage:true})}catch{}console.error(error);console.error('Renderer errors:',errors);if(page)try{console.error('UI toast:',await page.locator('#toast').textContent())}catch{};process.exitCode=1}finally{if(app)await app.close()}})();
