'use strict';
// Exercises the delivered archive, including the launcher, without changing source files.
const {_electron:electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),project=root;
const version=JSON.parse(fs.readFileSync(path.join(project,'app/package.json'),'utf8')).version;
const name=`Sangue-e-Cinzas-${version}-Linux-x64`,archive=process.env.LINUX_TEST_ARCHIVE||path.join(root,'dist',name+'.tar.gz');
const testRoot=path.join(project,'tmp/linux-test'),extract=path.join(testRoot,'Pasta com espaços e acentos — Linux'),out=path.join(project,'tmp/qa-linux');
fs.mkdirSync(out,{recursive:true});fs.rmSync(testRoot,{recursive:true,force:true});fs.mkdirSync(extract,{recursive:true});
assert.ok(fs.existsSync(archive),'Distribuição Linux ainda não criada: '+archive);
execFileSync('tar',['-xzf',archive,'-C',extract]);
const appDir=path.join(extract,name),exe=path.join(appDir,'sangue-e-cinzas'),launcher=path.join(appDir,'Iniciar-Sangue-e-Cinzas.sh'),dataFile=path.join(appDir,'dados/fichas.json');
assert.ok(fs.existsSync(exe));assert.ok(fs.existsSync(launcher));assert.equal(fs.existsSync(dataFile),false,'O pacote deve começar sem fichas de teste.');
for(const file of [exe,launcher])assert.ok(fs.statSync(file).mode&0o111,'Sem permissão de execução: '+file);
const isolatedEnv={...process.env,XDG_CONFIG_HOME:path.join(testRoot,'config'),XDG_CACHE_HOME:path.join(testRoot,'cache'),XDG_DATA_HOME:path.join(testRoot,'data')};
const noSandbox=process.env.LINUX_TEST_NO_SANDBOX==='1',args=['--disable-gpu',...(noSandbox?['--no-sandbox']:[])];
if(noSandbox)console.log('AVISO: LINUX_TEST_NO_SANDBOX=1 é uma exceção explícita para este teste. O pacote e lançador não são modificados.');
let app,page;const errors=[],checks=[];
const action=name=>page.locator(`[data-action="${name}"]`).first();
const check=name=>{checks.push(name);console.log('PASS '+name)};
async function nav(name){await page.locator(`.nav [data-view="${name}"]`).click();await page.waitForSelector('h1')}
async function field(key,value){const locator=page.locator(`[data-field="${key}"]`);await locator.fill(String(value));await locator.press('Tab')}
async function launch(executablePath=exe,extra=[]){
 app=await electron.launch({executablePath,args:[...args,...extra],env:isolatedEnv,chromiumSandbox:!noSandbox,timeout:45000});
 app.on('window',p=>p.on('pageerror',e=>errors.push(e.message)));
 page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('h1',{timeout:30000});
 const runtime=await app.evaluate(({app,BrowserWindow})=>({packaged:app.isPackaged,exec:process.execPath,data:app.getPath('userData'),noSandbox:app.commandLine.hasSwitch('no-sandbox'),sandbox:BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences().sandbox,platform:process.platform}));
 assert.equal(runtime.packaged,true);assert.equal(runtime.platform,'linux');assert.equal(runtime.exec,exe);assert.equal(runtime.sandbox,true);assert.equal(runtime.noSandbox,noSandbox);
 assert.equal(await page.evaluate(()=>storageBlocked),false);
 return runtime;
}
async function saveTo(name){const file=path.join(out,name);fs.rmSync(file,{force:true});await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},file);return file}
async function waitFile(file){for(let i=0;i<450;i++){if(fs.existsSync(file)&&fs.statSync(file).size>100)return;await page.waitForTimeout(100)}throw Error('Arquivo não criado: '+file+'; mensagem: '+await page.locator('#toast').textContent())}
async function close(){await page.evaluate(()=>flushSave());await app.close();app=null}
(async()=>{try{
 console.log('Validando o pacote Linux reextraído em caminho com espaços e acentos…');
 const runtime=await launch();assert.equal(runtime.data,path.join(appDir,'dados'));check('pacote real, modo portátil, caminho com espaços e sandbox do renderer');
 const views=['resumo','personagem','atributos','habilidades','vantagens','criacao','sessao','inventario','catalogo','biblioteca','modificadores','historico'];
 for(const view of views){await nav(view);assert.ok((await page.locator('h1').innerText()).length>0)}check('todas as 12 telas abrem sem erro');
 await nav('personagem');await field('name','Inês de Évora — Linux portátil');await field('player','João — teste de integração');await field('chronicle','Évora, 1242');await field('notes','Fichas compartilháveis; dados persistentes no Linux.');await page.locator('[data-field="clan"]').selectOption('Ventrue');assert.ok((await page.evaluate(()=>ch().weakness)).length>10);check('identidade com acentos e fraqueza do clã');
 await nav('modificadores');await action('new-bonus').click();await page.locator('#bonus-name').fill('Poder excepcional autorizado');await page.locator('#bonus-target').selectOption('attribute:strength');await page.locator('#bonus-value').fill('20000');await action('save-bonus').click();assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);assert.equal(await page.evaluate(()=>stats().attributes.strength),20001);await close();
 assert.equal(JSON.parse(fs.readFileSync(dataFile,'utf8')).characters[0].bonuses[0].value,20000);await launch();assert.equal(await page.evaluate(()=>ch().name),'Inês de Évora — Linux portátil');assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);check('salvamento adjacente e modificador +20000 preservado após reiniciar');
 await page.locator('.topbar [data-action="undo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses.length),0);await page.locator('.topbar [data-action="redo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);check('desfazer/refazer persistente após reiniciar');
 await nav('catalogo');await page.locator('#catalog-search').fill('Auspex');await page.waitForTimeout(250);await page.evaluate(()=>waitForSearch());await page.waitForFunction(()=>searchStates.catalog.result?.total>0&&!searchStates.catalog.result.pending);assert.ok(await page.locator('.catalog-card').count());await action('entry').click();assert.ok((await page.locator('.entry-text').innerText()).length>30);await action('close').click();check('catálogo pesquisável e referências dos poderes');
 await nav('biblioteca');await page.locator('#library-search').fill('Celerity');await page.waitForTimeout(250);await page.evaluate(()=>waitForSearch());await page.waitForFunction(()=>searchStates.library.result?.total>0&&!searchStates.library.result.pending);await action('read-page').click();assert.ok((await page.locator('.page-text').innerText()).length>100);await action('close').click();const opened=app.waitForEvent('window');await action('source').click();const pdf=await opened;await pdf.waitForLoadState('domcontentloaded');assert.ok(pdf.url().includes('.pdf'));await pdf.close();check('biblioteca offline, leitura textual e PDF original em janela nativa');
 const shared=await saveTo('linux.dav20.json');await page.locator('.topbar [data-action="export"]').click();await waitFile(shared);const exported=JSON.parse(fs.readFileSync(shared,'utf8'));assert.equal(exported.format,'vampire-dark-ages-v20');assert.equal(exported.characters[0].name,'Inês de Évora — Linux portátil');assert.equal(exported.characters[0].bonuses[0].value,20000);
 await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},shared);await page.locator('.topbar [data-action="import"]').click();await page.waitForFunction(()=>state.characters.length===2);assert.notEqual(await page.evaluate(()=>state.characters[0].id),await page.evaluate(()=>state.characters[1].id));assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);check('exportação/importação por IPC nativo preserva acentos, valores e cópia independente');
 const complete=await saveTo('linux-completo.pdf');await page.locator('.topbar [data-action="pdf"]').click();await waitFile(complete);assert.equal(fs.readFileSync(complete).subarray(0,5).toString(),'%PDF-');assert.ok(fs.statSync(complete).size>20000);check('PDF completo gerado pelo runtime Linux');
 await nav('biblioteca');const official=await saveTo('linux-oficial.pdf');await action('official-pdf').click();if(await page.locator('[data-action="confirm-official"]').count())await action('confirm-official').click();await waitFile(official);assert.equal(fs.readFileSync(official).subarray(0,5).toString(),'%PDF-');assert.ok(fs.statSync(official).size>50000);check('ficha oficial preenchida pelo runtime Linux');
 await nav('resumo');await page.screenshot({path:path.join(out,'linux.png'),fullPage:true});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(960,720));await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'linux-compacto.png'),fullPage:true});check('janela compacta sem rolagem horizontal');
 const windowsFixture=path.join(project,'tmp/qa-windows/windows.dav20.json');assert.ok(fs.existsSync(windowsFixture),'A ficha de referência exportada no Windows precisa estar disponível.');const windowsCharacter=JSON.parse(fs.readFileSync(windowsFixture,'utf8')).characters[0],existingIds=await page.evaluate(()=>state.characters.map(c=>c.id));
 await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},windowsFixture);await page.locator('.topbar [data-action="import"]').click();await page.waitForFunction(()=>state.characters.length===3);const importedWindows=await page.evaluate(()=>ch());assert.equal(importedWindows.name,windowsCharacter.name+' (importado)');assert.equal(importedWindows.bonuses[0].value,20000);assert.notEqual(importedWindows.id,windowsCharacter.id);assert.ok(!existingIds.includes(importedWindows.id));check('ficha realmente exportada no Windows é importada no Linux com acentos, +20000 e novo identificador');
 await close();const data=JSON.parse(fs.readFileSync(dataFile,'utf8'));assert.equal(data.characters.length,3);assert.equal(data.characters[1].bonuses[0].value,20000);
 await launch(launcher);assert.equal(await page.evaluate(()=>state.characters.length),3);assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);await close();check('lançador distribuído inicia o programa e mantém os dados portáteis');
 const explicit=path.join(testRoot,'perfil explícito');const customRuntime=await launch(exe,['--user-data-dir='+explicit]);assert.equal(customRuntime.data,explicit);assert.equal(await page.evaluate(()=>state.characters.length),1);assert.equal(await page.evaluate(()=>ch().bonuses.length),0);await close();assert.equal(JSON.parse(fs.readFileSync(dataFile,'utf8')).characters.length,3);check('perfil explícito é respeitado sem alterar os dados portáteis');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({result:'PASS',checks:checks.length,errors,sandbox:!noSandbox,archive,output:out},null,2));console.log(JSON.stringify({result:'PASS',checks:checks.length,errors,sandbox:!noSandbox,output:out},null,2));
}catch(error){if(page)try{await page.screenshot({path:path.join(out,'falha.png'),fullPage:true})}catch{}console.error(error.stack||error);console.error('Renderer errors:',errors);if(page)try{console.error('UI toast:',await page.locator('#toast').textContent())}catch{};console.error('O teste não desliga o sandbox automaticamente. Se o ambiente impedir namespaces, registrar a limitação antes de usar LINUX_TEST_NO_SANDBOX=1.');process.exitCode=1}finally{if(app)await app.close()}})();
