'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),project=root,prefix=path.join(project,'tmp/wine'),testDir=path.join(project,'tmp/windows-app'),qa=path.join(project,'tmp/qa-windows');
const version=JSON.parse(fs.readFileSync(path.join(project,'app/package.json'),'utf8')).version;
fs.mkdirSync(prefix,{recursive:true});fs.mkdirSync(qa,{recursive:true});fs.rmSync(testDir,{recursive:true,force:true});fs.cpSync(path.join(root,`dist/Sangue-e-Cinzas-${version}-Windows-x64`),testDir,{recursive:true});
const log=fs.openSync(path.join(qa,'wine.log'),'w'),env={...process.env,WINEPREFIX:prefix,WINEDEBUG:'-all',WINEDLLOVERRIDES:'mscoree,mshtml='};
const delay=ms=>new Promise(r=>setTimeout(r,ms));let socket,sequence=0;const pending=new Map();
async function inspector(){let url;for(let n=0;n<20;n++){try{const r=await fetch('http://127.0.0.1:9238/json/list');url=(await r.json())[0]?.webSocketDebuggerUrl;if(url)break}catch{}await delay(500)}if(!url)throw Error('Inspetor do processo Windows indisponível.');socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});socket.onmessage=e=>{const data=JSON.parse(e.data);if(data.id){const entry=pending.get(data.id);pending.delete(data.id);if(data.error)entry.reject(Error(data.error.message));else entry.resolve(data.result)}}}
async function mainEval(expression){const id=++sequence;const reply=new Promise((resolve,reject)=>pending.set(id,{resolve,reject}));socket.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));const data=await reply;if(data.exceptionDetails)throw Error(data.exceptionDetails.exception?.description||data.exceptionDetails.text);return data.result?.value}
const winPath=file=>'Z:'+file.replaceAll('/','\\');
async function mockSave(file){fs.rmSync(file,{force:true});await mainEval(`(process.mainModule.require('electron').dialog.showSaveDialog=async()=>({canceled:false,filePath:${JSON.stringify(winPath(file))}}),true)`)}
async function waitFile(file){for(let n=0;n<450;n++){if(fs.existsSync(file)&&fs.statSync(file).size>100)return;await delay(100)}throw Error('Arquivo Windows não criado: '+file)}
(async()=>{let proc,browser;try{
 console.log('Abrindo o executável Windows em ambiente isolado…');
 proc=spawn('wine',[path.join(testDir,'Sangue-e-Cinzas.exe'),'--no-sandbox','--disable-gpu','--remote-debugging-port=9338','--inspect=9238'],{env,stdio:['ignore',log,log]});
 let ready=false;for(let n=0;n<90;n++){try{const response=await fetch('http://127.0.0.1:9338/json/version');if(response.ok){ready=true;break}}catch{}await delay(1000);if(n===40)console.log('Aguardando a primeira inicialização do runtime Windows…')}
 if(!ready)throw Error('Executável não abriu: consulte tmp/qa-windows/wine.log.');
 browser=await chromium.connectOverCDP('http://127.0.0.1:9338');const context=browser.contexts()[0],page=context.pages()[0];const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('h1',{timeout:30000});assert.ok((await page.title()).includes('Sangue'));
 await page.locator('[data-view="personagem"]').click();await page.locator('[data-field="name"]').fill('Inês — teste Windows portátil');await page.locator('[data-field="clan"]').selectOption('Ventrue');assert.ok((await page.evaluate(()=>ch().weakness)).length>10);
 await page.locator('[data-view="modificadores"]').click();await page.locator('[data-action="new-bonus"]').first().click();await page.locator('#bonus-name').fill('Poder autorizado');await page.locator('#bonus-target').selectOption('attribute:strength');await page.locator('#bonus-value').fill('20000');await page.locator('[data-action="save-bonus"]').click();await page.evaluate(()=>flushSave());await page.reload();await page.waitForSelector('h1');assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);
 await page.locator('.topbar [data-action="undo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses.length),0);await page.locator('.topbar [data-action="redo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses[0].value),20000);
 await page.locator('[data-view="catalogo"]').click();await page.locator('#catalog-search').fill('auspex');await page.waitForFunction(()=>searchStates.catalog.result?.total>0&&!searchStates.catalog.result.pending);assert.ok(await page.locator('.catalog-card').count());
 await inspector();const json=path.join(qa,'windows.dav20.json');await mockSave(json);await page.locator('.topbar [data-action="export"]').click();await waitFile(json);assert.equal(JSON.parse(fs.readFileSync(json)).characters[0].bonuses[0].value,20000);
 const complete=path.join(qa,'completo.pdf');await mockSave(complete);await page.locator('.topbar [data-action="pdf"]').click();await waitFile(complete);
 const official=path.join(qa,'oficial.pdf');await mockSave(official);await page.locator('[data-view="biblioteca"]').click();await page.locator('[data-action="official-pdf"]').click();if(await page.locator('[data-action="confirm-official"]').count())await page.locator('[data-action="confirm-official"]').click();await waitFile(official);
 await page.evaluate(()=>flushSave());const data=JSON.parse(fs.readFileSync(path.join(testDir,'dados/fichas.json'),'utf8'));assert.equal(data.format,'vampire-dark-ages-v20');assert.equal(data.characters[0].name,'Inês — teste Windows portátil');assert.equal(data.characters[0].bonuses[0].value,20000);assert.deepEqual(errors,[]);
 await page.locator('[data-view="resumo"]').click();await page.screenshot({path:path.join(qa,'windows.png'),fullPage:true});console.log('PASS: executável Windows, acentos, busca, +20000, histórico, dados portáteis, JSON e ambos os PDFs sob Wine.');
 }catch(e){if(browser){const p=browser.contexts()[0].pages()[0];if(p){console.error('Mensagem da interface:',await p.locator('#toast').textContent().catch(()=>''));await p.screenshot({path:path.join(qa,'failure.png'),fullPage:true}).catch(()=>{})}}console.error(e.stack||e);process.exitCode=1}finally{if(socket)socket.close();if(browser)await browser.close();if(proc)proc.kill('SIGTERM');spawn('wineserver',['-k'],{env,stdio:'ignore'});fs.closeSync(log)}})();
