(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.Rules=factory()})(globalThis,function(){
'use strict';
const MAX=Number.MAX_SAFE_INTEGER, FORMAT='vampire-dark-ages-v20';
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function number(value,label='Valor',min=-MAX,max=MAX,integer=false){if(!['number','string'].includes(typeof value))throw Error(`${label}: informe um número válido. O valor não foi alterado.`);const n=Number(value);if(typeof value==='string'&&!value.trim()||value==null||!Number.isFinite(n)||Math.abs(n)>MAX||n<min||n>max||(integer&&!Number.isSafeInteger(n)))throw Error(`${label}: informe ${integer?'um inteiro':'um número'} entre ${min.toLocaleString('pt-BR')} e ${max.toLocaleString('pt-BR')}. O valor não foi alterado.`);return n}
const safe=n=>number(n,'Resultado do cálculo',-MAX,MAX,true);
const sum=values=>values.reduce((a,b)=>safe(a+b),0);
const attributes=['strength','dexterity','stamina','charisma','manipulation','appearance','perception','intelligence','wits'];
const attributeGroups={physical:['strength','dexterity','stamina'],social:['charisma','manipulation','appearance'],mental:['perception','intelligence','wits']};
const groupLabels={physical:'Físicos',social:'Sociais',mental:'Mentais',talents:'Talentos',skills:'Perícias',knowledges:'Conhecimentos'};
const abilityGroups={talents:['alertness','athletics','awareness','brawl','empathy','expression','intimidation','leadership','legerdemain','subterfuge'],skills:['animalKen','archery','commerce','crafts','etiquette','melee','performance','ride','stealth','survival'],knowledges:['academics','enigmas','hearthWisdom','investigation','law','medicine','occult','politics','seneschal','theology']};
const labels={strength:'Força',dexterity:'Destreza',stamina:'Vigor',charisma:'Carisma',manipulation:'Manipulação',appearance:'Aparência',perception:'Percepção',intelligence:'Inteligência',wits:'Raciocínio',alertness:'Prontidão',athletics:'Esportes',awareness:'Consciência',brawl:'Briga',empathy:'Empatia',expression:'Expressão',intimidation:'Intimidação',leadership:'Liderança',legerdemain:'Prestidigitação',subterfuge:'Subterfúgio',animalKen:'Empatia com Animais',archery:'Arqueria',commerce:'Comércio',crafts:'Ofícios',etiquette:'Etiqueta',melee:'Armas Brancas',performance:'Performance',ride:'Cavalgar',stealth:'Furtividade',survival:'Sobrevivência',academics:'Acadêmicos',enigmas:'Enigmas',hearthWisdom:'Sabedoria Popular',investigation:'Investigação',law:'Direito',medicine:'Medicina',occult:'Ocultismo',politics:'Política',seneschal:'Senescalia',theology:'Teologia',moral:'Consciência / Convicção',restraint:'Autocontrole / Instinto',courage:'Coragem',conscience:'Consciência',conviction:'Convicção',selfControl:'Autocontrole',instinct:'Instinto',willpower:'Força de Vontade',road:'Caminho',blood:'Sangue',dice:'Parada de dados',difficulty:'Dificuldade',initiative:'Iniciativa'};
const abilityDefinitions=Object.entries(abilityGroups).flatMap(([group,keys])=>keys.map(key=>({key,label:labels[key],group})));
const abilityKeys=abilityDefinitions.map(a=>a.key), virtueKeys=['moral','restraint','courage'];
const generationTable={4:{traitMax:9,bloodMax:50,bloodPerTurn:10},5:{traitMax:8,bloodMax:40,bloodPerTurn:8},6:{traitMax:7,bloodMax:30,bloodPerTurn:6},7:{traitMax:6,bloodMax:20,bloodPerTurn:4},8:{traitMax:5,bloodMax:15,bloodPerTurn:3},9:{traitMax:5,bloodMax:14,bloodPerTurn:2},10:{traitMax:5,bloodMax:13,bloodPerTurn:1},11:{traitMax:5,bloodMax:12,bloodPerTurn:1},12:{traitMax:5,bloodMax:11,bloodPerTurn:1},13:{traitMax:5,bloodMax:10,bloodPerTurn:1}};
const freebieCosts={attribute:5,ability:2,discipline:7,background:1,virtue:2,road:2,willpower:1,path:4};
const traitTypes=[{key:'attribute',label:'Atributo'},{key:'ability',label:'Habilidade'},{key:'discipline',label:'Disciplina'},{key:'background',label:'Antecedente'},{key:'virtue',label:'Virtude'},{key:'road',label:'Caminho'},{key:'willpower',label:'Força de Vontade'},{key:'path',label:'Trilha de magia'},{key:'ritual',label:'Ritual'}];
const bonusTargets=[...attributes.map(k=>`attribute:${k}`),...abilityKeys.map(k=>`ability:${k}`),'dice','difficulty','initiative','bloodMax','bloodPerTurn','traitMax'];
const healthLevels=[{label:'Escoriado',penalty:0},{label:'Machucado',penalty:-1},{label:'Ferido',penalty:-1},{label:'Ferido Gravemente',penalty:-2},{label:'Espancado',penalty:-2},{label:'Aleijado',penalty:-5},{label:'Incapacitado',penalty:null}];
const torporTimes=['Um milênio ou mais','Cinco séculos','Um século','Cinco décadas','Uma década','Um ano','Um mês','Duas semanas','Uma semana','Três dias','Um dia'];
const listNames=['disciplines','backgrounds','paths','rituals','merits','flaws','inventory','bonuses','journal','rolls'];
const identityFields=['name','player','chronicle','concept','clan','sire','nature','demeanor','sect','haven','road','birth','embrace','appearance','history','notes','portrait','weakness','bloodPreference'];
function create(name='Novo vampiro'){const now=new Date().toISOString();return {id:uid(),name,player:'',chronicle:'',concept:'',clan:'',sire:'',nature:'',demeanor:'',sect:'',haven:'',road:'Road of Humanity',birth:'',embrace:'',appearance:'',history:'',notes:'',portrait:'',weakness:'',bloodPreference:'',generation:12,rulesMode:'standard',attributes:Object.fromEntries(attributes.map(k=>[k,1])),abilities:Object.fromEntries(abilityKeys.map(k=>[k,0])),virtues:{moral:1,restraint:1,courage:1},virtueTypes:{moral:'conscience',restraint:'selfControl'},roadScore:2,willpower:1,resources:{blood:0,willpower:1},health:{bashing:0,lethal:0,aggravated:0,state:'active'},specialties:{},conditions:[],disciplines:[],backgrounds:[],paths:[],rituals:[],merits:[],flaws:[],inventory:[],bonuses:[],journal:[],rolls:[],creation:{phase:'allocation',attributePriorities:['physical','social','mental'],abilityPriorities:['talents','skills','knowledges'],freebieBudget:15,flawCreditLimit:7,base:null},experience:{total:0,spent:0,ledger:[]},campaign:{traitLimit:null,bloodMax:null,bloodPerTurn:null},createdAt:now,updatedAt:now}}
function generationStats(generation){const g=number(generation,'Geração',3,MAX,true);if(g===3)return {traitMax:10,bloodMax:null,bloodPerTurn:null};return {...generationTable[Math.min(13,g)]}}
const isNosferatu=c=>['nosferatu'].includes(normalize(c.clan));
const baselineAttribute=(c,key)=>key==='appearance'&&isNosferatu(c)?0:1;
function bonusSources(c,target){return (c.bonuses||[]).filter(b=>b.target===target&&b.enabled!==false&&(b.duration!=='turns'||b.remaining>0)).map(b=>({label:b.name,value:number(b.value,b.name,-MAX,MAX,true)}))}
const bonusTotal=(c,target)=>sum(bonusSources(c,target).map(b=>b.value));
const disciplineRating=(c,names)=>Math.max(0,...c.disciplines.filter(i=>names.includes(normalize(i.name))).map(i=>i.rating));
function attributeSources(c,key){const sources=bonusSources(c,`attribute:${key}`),passive={strength:['Potence','Potência'],dexterity:['Celerity','Rapidez'],stamina:['Fortitude','Fortitude']}[key];if(passive){const value=disciplineRating(c,passive.map(normalize));if(value)sources.push({label:passive[0]+' — dados passivos',value})}if(key==='dexterity')for(const i of c.inventory)if(i.equipped&&i.type==='armor'&&i.penalty)sources.push({label:i.name+' — penalidade da armadura',value:-Math.abs(i.penalty)});return sources}
function currentRatings(c){return {attributes:{...c.attributes},abilities:{...c.abilities},virtues:{...c.virtues},disciplines:c.disciplines.map(i=>({...i})),backgrounds:c.backgrounds.map(i=>({...i})),paths:c.paths.map(i=>({...i})),rituals:c.rituals.map(i=>({...i})),roadScore:c.creation.phase==='allocation'?safe(c.virtues.moral+c.virtues.restraint):c.roadScore,willpower:c.creation.phase==='allocation'?c.virtues.courage:c.willpower,clan:c.clan,attributePriorities:[...c.creation.attributePriorities],abilityPriorities:[...c.creation.abilityPriorities]}}
function creationAllocation(c){const base=c.creation.base||currentRatings(c), attr={},ability={};for(const [group,keys] of Object.entries(attributeGroups))attr[group]=sum(keys.map(key=>safe(base.attributes[key]-(key==='appearance'&&normalize(base.clan)==='nosferatu'?0:1))));for(const [group,keys] of Object.entries(abilityGroups))ability[group]=sum(keys.map(key=>base.abilities[key]));return {attributes:attr,abilities:ability,disciplines:sum(base.disciplines.map(i=>i.rating)),backgrounds:sum(base.backgrounds.filter(i=>!i.granted).map(i=>i.rating)),virtues:sum(virtueKeys.map(k=>safe(base.virtues[k]-1))),base}}
function purchaseEntries(c){const base=c.creation.base;if(!base)return [];const entries=[],xp=c.experience.ledger||[];function add(type,key,label,from,to,unit){const acquired=sum(xp.filter(x=>x.type===type&&x.key===key).map(x=>safe(x.to-x.from)));const delta=safe(to-from-acquired);if(delta)entries.push({type,key,label,from,to,delta,cost:safe(delta*unit)})}
 for(const k of attributes)add('attribute',k,labels[k],base.attributes[k],c.attributes[k],5);for(const k of abilityKeys)add('ability',k,labels[k],base.abilities[k],c.abilities[k],2);for(const k of virtueKeys)add('virtue',k,labels[k],base.virtues[k],c.virtues[k],2);
 for(const [type,list] of [['discipline','disciplines'],['background','backgrounds'],['path','paths']]){const ids=new Set([...base[list].map(i=>i.id),...c[list].map(i=>i.id)]);for(const id of ids){const before=base[list].find(i=>i.id===id),after=c[list].find(i=>i.id===id);if(after?.granted||before?.granted)continue;add(type,id,after?.name||before?.name,type==='path'?0:(before?.rating||0),after?.rating||0,freebieCosts[type])}}
 add('road','road',labels.road,base.roadScore,c.roadScore,2);add('willpower','willpower',labels.willpower,base.willpower,c.willpower,1);
 for(const r of c.rituals)if(!r.granted&&!xp.some(x=>x.type==='ritual'&&x.key===r.id))entries.push({type:'ritual',key:r.id,label:r.name,from:0,to:r.rating,delta:r.rating,cost:r.rating});return entries
}
function validateNumbers(c){for(const k of attributes)number(c.attributes[k],labels[k],0,MAX,true);for(const k of abilityKeys)number(c.abilities[k],labels[k],0,MAX,true);for(const k of virtueKeys)number(c.virtues[k],labels[k],0,MAX,true);number(c.generation,'Geração',3,MAX,true);number(c.roadScore,'Caminho',0,MAX,true);number(c.willpower,'Força de Vontade',0,MAX,true);for(const k of ['blood','willpower'])number(c.resources[k],labels[k],0,MAX,true);for(const k of ['bashing','lethal','aggravated'])number(c.health[k],'Dano',0,7,true);if(sum(['bashing','lethal','aggravated'].map(k=>c.health[k]))>7)throw Error('A trilha de Vitalidade tem sete níveis. Use Aplicar dano para resolver o excesso.');for(const list of ['disciplines','backgrounds','paths','rituals'])for(const i of c[list])number(i.rating,i.name,0,MAX,true);for(const list of ['merits','flaws'])for(const i of c[list])number(i.cost,i.name,0,MAX,true);for(const b of c.bonuses){number(b.value,b.name,-MAX,MAX,true);number(b.remaining??0,'Duração do modificador',0,MAX,true);if(!bonusTargets.includes(b.target))throw Error('Destino de modificador desconhecido: '+b.target)}for(const k of ['total','spent'])number(c.experience[k],'Experiência',0,MAX,true);number(c.creation.freebieBudget,'Pontos de bônus',0,MAX,true);number(c.creation.flawCreditLimit,'Crédito máximo de defeitos',0,MAX,true);for(const k of ['traitLimit','bloodMax','bloodPerTurn'])if(c.campaign[k]!=null)number(c.campaign[k],k,0,MAX,true);for(const i of c.inventory){number(i.quantity,'Quantidade',0,MAX,true);if(i.weight!=null)number(i.weight,'Peso',0,MAX);for(const k of ['damage','armor','penalty'])if(i[k]!=null)number(i[k],k,k==='armor'?0:-MAX,MAX,true)}}
function calculate(c){validateNumbers(c);const warnings=[],standard=c.rulesMode!=='free',stats=generationStats(c.generation);const cap=(key,override)=>{const value=c.campaign[override]??stats[key];return value===null?null:Math.max(0,safe(value+bonusTotal(c,key)))};const traitMax=cap('traitMax','traitLimit'),bloodMax=cap('bloodMax','bloodMax'),bloodPerTurn=cap('bloodPerTurn','bloodPerTurn');
 const effective={attributes:Object.fromEntries(attributes.map(k=>[k,Math.max(0,safe(c.attributes[k]+sum(attributeSources(c,k).map(x=>x.value))))])),abilities:Object.fromEntries(abilityKeys.map(k=>[k,Math.max(0,safe(c.abilities[k]+bonusTotal(c,`ability:${k}`)))]))};
 const allocation=creationAllocation(c),purchases=purchaseEntries(c),negativePurchases=purchases.filter(x=>x.delta<0);const meritCost=sum(c.merits.map(i=>i.cost)),flawTotal=sum(c.flaws.map(i=>i.cost)),flawCredit=Math.min(flawTotal,c.creation.flawCreditLimit);const freebieSpent=sum([meritCost,...purchases.filter(x=>x.delta>0).map(x=>x.cost)]),freebieAvailable=safe(c.creation.freebieBudget+flawCredit),freebieRemaining=safe(freebieAvailable-freebieSpent);
 function allocationWarning(label,actual,wanted){if(actual!==wanted)warnings.push(`${label}: ${actual} / ${wanted} pontos na distribuição inicial.`)}
 if(standard){const attrOrder=allocation.base.attributePriorities,abilityOrder=allocation.base.abilityPriorities;attrOrder.forEach((g,index)=>allocationWarning(`Atributos ${groupLabels[g]}`,allocation.attributes[g],[7,5,3][index]));abilityOrder.forEach((g,index)=>allocationWarning(`Habilidades — ${groupLabels[g]}`,allocation.abilities[g],[13,9,5][index]));allocationWarning('Disciplinas',allocation.disciplines,4);allocationWarning('Antecedentes',allocation.backgrounds,5);allocationWarning('Virtudes além dos três pontos iniciais',allocation.virtues,7);
  for(const k of attributes){if(c.attributes[k]<baselineAttribute(c,k))warnings.push(`${labels[k]} está abaixo do valor inicial do clã.`);if(c.attributes[k]>traitMax)warnings.push(`${labels[k]} ${c.attributes[k]} supera o limite ${traitMax} da geração/campanha.`)}
  for(const k of abilityKeys){if(c.abilities[k]>traitMax)warnings.push(`${labels[k]} supera o limite ${traitMax} da geração/campanha.`);if(allocation.base.abilities[k]>3)warnings.push(`${labels[k]} tem mais de três pontos na distribuição inicial; use os pontos de bônus depois de registrar a base.`)}
  for(const [label,list] of [['Disciplina',c.disciplines],['Antecedente',c.backgrounds]])for(const i of list)if(i.rating>traitMax)warnings.push(`${label} ${i.name} supera o limite ${traitMax} da geração/campanha.`);
  for(const i of allocation.base.disciplines)if(i.rating>0&&i.inClan===false&&normalize(c.clan)!=='caitiff')warnings.push(`${i.name} é de fora do clã e não pode receber os quatro pontos iniciais; compre depois com bônus.`);
  for(const k of virtueKeys)if(c.virtues[k]<1||c.virtues[k]>5)warnings.push(`${labels[k]} deve ficar entre 1 e 5 pelas regras básicas.`);
  if(flawTotal>c.creation.flawCreditLimit)warnings.push(`Defeitos somam ${flawTotal}; apenas ${flawCredit} geram pontos de bônus.`);
  if(isNosferatu(c)&&c.attributes.appearance!==0)warnings.push('A maldição Nosferatu fixa Aparência em zero; qualquer exceção precisa ser acordada com o Narrador.');
  const generationBackground=sum(c.backgrounds.filter(i=>['generation','geracao'].includes(normalize(i.name))).map(i=>i.rating));const thirteenth=c.flaws.some(i=>['thirteenth generation','decima terceira geracao','13a geracao'].includes(normalize(i.name))),expectedGeneration=thirteenth?13:12-generationBackground;if(c.generation!==expectedGeneration)warnings.push(`Geração ${c.generation} difere da geração inicial esperada ${expectedGeneration}, considerando ${generationBackground} pontos de Geração. Registre a justificativa se houve diablerie ou ajuste do Narrador.`)
 }
 for(const list of ['disciplines','backgrounds']){const seen=new Set();for(const item of c[list]){const key=normalize(item.name);if(seen.has(key))warnings.push(`${item.name} aparece mais de uma vez. A distribuição soma os registros; dados passivos usam apenas o maior valor para evitar somar a mesma Disciplina duas vezes.`);seen.add(key)}}
 for(const p of negativePurchases)warnings.push(`${p.label} foi reduzido abaixo da base de criação mais as compras de XP; a redução não devolve bônus automaticamente.`);
 if(c.creation.base&&freebieRemaining<0)warnings.push(`Os pontos de bônus excedem o orçamento em ${-freebieRemaining}.`);if(!c.creation.base&&c.creation.phase!=='allocation')warnings.push('A base de criação não foi registrada; a auditoria de bônus não pode separar criação, bônus e XP.');
 const roadScore=c.creation.phase==='allocation'?safe(c.virtues.moral+c.virtues.restraint):c.roadScore,willpowerMax=c.creation.phase==='allocation'?c.virtues.courage:c.willpower;
 if(standard&&(roadScore>10||roadScore<1))warnings.push('O Caminho deve ficar entre 1 e 10. Zero representa a perda do personagem para a Besta.');if(standard&&(willpowerMax<1||willpowerMax>10))warnings.push('Força de Vontade permanente deve ficar entre 1 e 10.');
 if(c.generation>13)warnings.push('A tabela do núcleo agrupa gerações 13 ou superiores; esta geração não tem regras próprias de criação aqui e precisa da definição do Narrador.');if(bloodMax===null)warnings.push('O livro não define um valor de sangue para a Terceira Geração. Configure os limites da campanha para controlar recursos.');if(bloodMax!==null&&c.resources.blood>bloodMax)warnings.push(`Sangue atual ${c.resources.blood} supera o máximo ${bloodMax}. O valor foi preservado.`);if(c.resources.willpower>willpowerMax)warnings.push(`Força de Vontade atual ${c.resources.willpower} supera o valor permanente ${willpowerMax}. O valor foi preservado.`);if(c.experience.spent>c.experience.total)warnings.push('A experiência gasta supera a experiência recebida.');
 const totalDamage=sum([c.health.bashing,c.health.lethal,c.health.aggravated]),fullBashing=totalDamage===7&&c.health.bashing===7,state=c.health.state||'active';const canAct=state==='active'&&(totalDamage<7||fullBashing)&&!(c.conditions||[]).some(x=>['estacado','staked','inconsciente','unconscious'].includes(normalize(x)));if(totalDamage===7&&c.health.bashing===0&&state==='active')warnings.push('A trilha cheia com dano letal/agravado exige resolver torpor ou Morte Final; nenhum dado da Vitalidade foi alterado.');const healthPenalty=totalDamage===0?0:fullBashing?-5:healthLevels[totalDamage-1].penalty;const healthLabel=state==='finalDeath'?'Morte Final':state==='torpor'?'Torpor':totalDamage===0?'Ileso':fullBashing?'Incapacitado por dano contundente':healthLevels[totalDamage-1].label;
 const healthTrack=[...Array(c.health.aggravated).fill('aggravated'),...Array(c.health.lethal).fill('lethal'),...Array(c.health.bashing).fill('bashing'),...Array(7-totalDamage).fill(null)];const initiative=safe(effective.attributes.dexterity+effective.attributes.wits+bonusTotal(c,'initiative')+(healthPenalty||0));
 const fortitude=disciplineRating(c,['fortitude']),armor=sum(c.inventory.filter(i=>i.equipped&&i.type==='armor').map(i=>i.armor||0)),soak={bashing:safe(effective.attributes.stamina+armor),lethal:safe(effective.attributes.stamina+armor),aggravated:safe(fortitude+armor),fireSunlight:fortitude};
 const breakdown={attributes:Object.fromEntries(attributes.map(k=>[k,{base:c.attributes[k],sources:attributeSources(c,k),total:effective.attributes[k]}])),abilities:Object.fromEntries(abilityKeys.map(k=>[k,{base:c.abilities[k],sources:bonusSources(c,`ability:${k}`),total:effective.abilities[k]}])),initiative:{dexterity:effective.attributes.dexterity,wits:effective.attributes.wits,sources:bonusSources(c,'initiative'),healthPenalty:healthPenalty||0,total:initiative},blood:{generation:c.generation,base:stats.bloodMax,override:c.campaign.bloodMax,sources:bonusSources(c,'bloodMax'),total:bloodMax}};
 return {effective,attributes:effective.attributes,abilities:effective.abilities,virtues:{...c.virtues},attributeRatings:{...c.attributes},traitMax,bloodMax,bloodPerTurn,willpowerMax,roadScore,initiative,healthPenalty,healthLabel,healthTrack,totalDamage,canAct,soak,torporLength:torporTimes[Math.min(10,Math.max(0,roadScore))],selfControlPool:Math.min(c.virtues.restraint,c.resources.blood),warnings,breakdown,allocation,freebieSpent,freebieAvailable,freebieRemaining,xpAvailable:safe(c.experience.total-c.experience.spent),experienceRemaining:safe(c.experience.total-c.experience.spent),creation:{phase:c.creation.phase,allocation,purchases,freebieSpent,freebieAvailable,freebieRemaining,meritCost,flawTotal,flawCredit,baseRecorded:!!c.creation.base},diceModifier:bonusTotal(c,'dice'),difficultyModifier:bonusTotal(c,'difficulty')}
}
function setClan(c,clan){const before=isNosferatu(c);c.clan=String(clan);if(c.creation.phase==='allocation'){if(isNosferatu(c))c.attributes.appearance=0;else if(before&&c.attributes.appearance===0)c.attributes.appearance=1}return c}
function setRoad(c,road,virtues={}){c.road=String(road);if(virtues.moral)c.virtueTypes.moral=virtues.moral;if(virtues.restraint)c.virtueTypes.restraint=virtues.restraint;return c}
function freezeCreation(c){if(c.creation.base)throw Error('A base de criação já está registrada. Desfaça a transição para editar a distribuição inicial.');const s=calculate(c);c.roadScore=s.roadScore;c.willpower=s.willpowerMax;c.creation.base=currentRatings(c);c.creation.phase='freebies';return calculate(c)}
function enterPlay(c){if(!c.creation.base)throw Error('Registre a distribuição inicial antes de iniciar a crônica.');c.creation.phase='play';return calculate(c)}
function spend(c,resource,amount){if(!['blood','willpower'].includes(resource))throw Error('Recurso desconhecido.');const n=number(amount,'Gasto',0,MAX,true);if(c.resources[resource]<n)throw Error(`${labels[resource]} insuficiente: você possui ${c.resources[resource]} e o gasto é ${n}.`);c.resources[resource]=safe(c.resources[resource]-n);return c.resources[resource]}
function recover(c,resource,amount){if(!['blood','willpower'].includes(resource))throw Error('Recurso desconhecido.');const n=number(amount,'Recuperação',0,MAX,true),s=calculate(c),limit=resource==='blood'?s.bloodMax:s.willpowerMax,value=safe(c.resources[resource]+n);if(limit!==null&&value>limit)throw Error(`${labels[resource]} resultante ${value} supera o máximo ${limit}; informe apenas a recuperação que cabe na reserva.`);c.resources[resource]=value;return value}
function roll(c,options={},rng=Math.random){const s=calculate(c),base=number(options.pool??0,'Parada de dados',0,MAX,true),modifier=number(options.modifier??0,'Modificador',-MAX,MAX,true);const reflexive=options.reflexive||options.soak;const wound=reflexive||options.healthPenalty===false?0:(s.healthPenalty||0);if(c.health.state==='finalDeath')throw Error('Morte Final não permite ações ou absorção de dano.');if(!s.canAct&&!reflexive)throw Error('O personagem está incapaz de agir. Apenas cura e ações autorizadas pelo Narrador estão disponíveis.');const pool=Math.max(0,safe(base+modifier+s.diceModifier+wound));if(pool>100000)throw Error(`A parada calculada tem ${pool.toLocaleString('pt-BR')} dados. O limite de uma rolagem é 100.000 dados para preservar o desempenho; os valores da ficha continuam intactos.`);const ability=options.ability?abilityDefinitions.find(a=>a.key===options.ability):null;if(options.ability&&!ability)throw Error('Habilidade da rolagem desconhecida.');if(ability&&c.abilities[ability.key]===0&&ability.group==='knowledges'&&c.rulesMode!=='free'&&!options.allowUntrainedKnowledge)throw Error('Conhecimentos com valor zero não podem ser usados sem uma decisão do Narrador.');const untrained=ability&&c.abilities[ability.key]===0&&ability.group==='skills'?1:0;const difficulty=number(safe(number(options.difficulty??6,'Dificuldade',2,10,true)+s.difficultyModifier+untrained),'Dificuldade final',2,10,true);if(options.willpower&&c.resources.willpower<1)throw Error('Não há Força de Vontade disponível para garantir um sucesso.');const specialty=!!options.specialty,dice=[];let raw=0,ones=0;for(let i=0;i<pool;i++){const r=rng();if(!Number.isFinite(r)||r<0||r>=1)throw Error('O gerador de dados deve retornar um valor entre 0 e 1.');const d=Math.floor(r*10)+1;dice.push(d);if(d===1)ones++;else if(d>=difficulty)raw+=specialty&&d===10?2:1}const automatic=options.willpower?1:0,net=Math.max(0,raw-ones),successes=safe(net+automatic),botch=options.damage||options.soak?false:raw===0&&ones>0&&automatic===0;const outcome=botch?'Falha crítica':successes===0?'Falha':successes===1?'Sucesso marginal':successes===2?'Sucesso moderado':successes===3?'Sucesso completo':successes===4?'Sucesso excepcional':'Sucesso fenomenal';return {pool,base,modifier,difficulty,dice,ones,rawSuccesses:raw,successes,automatic,botch,outcome,healthPenalty:wound,untrainedPenalty:untrained,specialty,willpowerCost:automatic,explanation:`${base} dados + (${modifier}) ajuste + (${s.diceModifier}) modificadores + (${wound}) ferimentos = ${pool}; dificuldade ${difficulty}${untrained?' (inclui +1 por Perícia sem treinamento)':''}. ${raw} sucessos nos dados − ${ones} resultados 1 = ${net}; ${automatic} sucesso garantido. ${specialty?'Os resultados 10 contam como dois sucessos. ':''}${botch?'Nenhum sucesso saiu nos dados e houve pelo menos um resultado 1.':''}`,at:new Date().toISOString()}}
function rollInitiative(c,rng=Math.random){const s=calculate(c);if(!s.canAct)throw Error('O personagem não pode agir.');const r=rng();if(!Number.isFinite(r)||r<0||r>=1)throw Error('Gerador de dados inválido.');const die=Math.floor(r*10)+1;return {die,total:safe(die+s.initiative),base:s.initiative,explanation:`1d10 (${die}) + Destreza ${s.effective.attributes.dexterity} + Raciocínio ${s.effective.attributes.wits} + modificadores ${bonusTotal(c,'initiative')} + ferimentos ${s.healthPenalty||0} = ${safe(die+s.initiative)}`}}
function applyDamage(c,type,amount,options={}){if(!['bashing','lethal','aggravated'].includes(type))throw Error('Tipo de dano desconhecido.');let incoming=number(amount,'Dano após absorção',0,MAX,true);if(type==='bashing'&&options.halveBashing!==false)incoming=Math.floor(incoming/2);const applied=incoming,h={...c.health};if(h.state==='finalDeath')throw Error('O personagem já está em Morte Final.');if(type==='aggravated'&&incoming>0&&(h.state==='torpor'||sum([h.bashing,h.lethal,h.aggravated])===7)){h.state='finalDeath';c.health=h;return {applied,state:h.state,explanation:'Dano agravado em um Cainita incapacitado ou em torpor causa Morte Final.'}}const maxSteps=Math.min(incoming,22);for(let step=0;step<maxSteps;step++){if(h.state==='finalDeath')break;const total=sum([h.bashing,h.lethal,h.aggravated]);if(total<7)h[type]++;else if(type==='aggravated'){h.state='finalDeath';break}else if(type==='lethal'){if(h.bashing>0){h.bashing--;h.lethal++}else if(h.lethal>0){h.lethal--;h.aggravated++}}else if(h.bashing>0){h.bashing--;h.lethal++}else if(h.lethal>0){h.lethal--;h.aggravated++}else {h.state='finalDeath';break}if(h.aggravated===7)h.state='finalDeath';else if(sum([h.bashing,h.lethal,h.aggravated])===7&&(h.bashing===0||c.resources.blood===0))h.state='torpor'}if(incoming>22)h.state='finalDeath';c.health=h;return {applied,state:h.state,explanation:`${applied} nível(is) aplicado(s) após absorção${type==='bashing'&&options.halveBashing!==false?' e divisão por dois, arredondando para baixo':''}. Os ferimentos mais graves ocupam o início da trilha.`}}
function heal(c,type,levels=1,options={}){if(!['bashing','lethal','aggravated'].includes(type))throw Error('Tipo de dano desconhecido.');const n=number(levels,'Níveis a curar',1,7,true),s=calculate(c);if(c.health.state==='finalDeath')throw Error('Morte Final não pode ser curada.');if(c.health.state==='torpor')throw Error('Torpor exige repouso, sangue externo e despertar conforme o Caminho; confirme o despertar e altere a condição antes da cura.');if(c.health[type]<n)throw Error('Não há essa quantidade de ferimentos desse tipo para curar.');const cost=safe(n*(type==='aggravated'?5:1));if(type==='aggravated'&&!options.rested)throw Error('A cura de dano agravado exige um dia completo de repouso e cinco pontos de sangue por nível.');if(type!=='aggravated'&&s.bloodPerTurn!==null&&cost>s.bloodPerTurn)throw Error(`Esta cura usa ${cost} pontos de sangue e supera ${s.bloodPerTurn} por turno. Divida em turnos.`);if(c.resources.blood<cost)throw Error(`Sangue insuficiente: esta cura custa ${cost}.`);c.resources.blood-=cost;c.health[type]-=n;return {levels:n,cost,type}}
function advanceTurn(c){const expired=[];for(const b of c.bonuses)if(b.enabled!==false&&b.duration==='turns'){if(b.remaining>0)b.remaining--;if(b.remaining===0){b.enabled=false;expired.push(b.name)}}return expired}
function endScene(c){const expired=[];for(const b of c.bonuses)if(b.enabled!==false&&['scene','turns'].includes(b.duration)){b.enabled=false;if(b.duration==='turns')b.remaining=0;expired.push(b.name)}return expired}
function startNight(c){const maximum=calculate(c).willpowerMax;if(c.health.state==='torpor'||c.health.state==='finalDeath')throw Error('Um Cainita em torpor ou Morte Final não desperta normalmente.');if(c.resources.blood<1)throw Error('Não há sangue para despertar. Resolva alimentação/torpor com o Narrador.');spend(c,'blood',1);if(c.resources.willpower<maximum)c.resources.willpower=safe(c.resources.willpower+1);return {bloodSpent:1,willpower:c.resources.willpower}}
function getTrait(c,type,key){if(type==='attribute'){if(!attributes.includes(key))throw Error('Atributo desconhecido.');return {rating:c.attributes[key],label:labels[key],set:n=>c.attributes[key]=n,max:calculate(c).traitMax}}if(type==='ability'){if(!abilityKeys.includes(key))throw Error('Habilidade desconhecida.');return {rating:c.abilities[key],label:labels[key],set:n=>c.abilities[key]=n,max:calculate(c).traitMax}}if(type==='virtue'){if(!virtueKeys.includes(key))throw Error('Virtude desconhecida.');return {rating:c.virtues[key],label:labels[key],set:n=>c.virtues[key]=n,max:5}}if(type==='road'||type==='willpower'){const field=type==='road'?'roadScore':'willpower';return {rating:c[field],label:labels[type],set:n=>c[field]=n,max:10}}const lists={discipline:'disciplines',background:'backgrounds',path:'paths',ritual:'rituals'};if(!lists[type])throw Error('Tipo de compra desconhecido.');const item=c[lists[type]].find(i=>i.id===key);if(!item)throw Error('Adicione a opção à ficha com valor zero antes de comprar com XP.');return {rating:item.rating,label:item.name,inClan:item.inClan,set:n=>item.rating=n,max:['path','ritual'].includes(type)?5:calculate(c).traitMax,item}}
function experienceCost(type,current,options={}){const n=number(current,'Valor atual',0,MAX,true);if(type==='attribute')return safe(n*4);if(type==='ability')return n===0?3:safe(n*2);if(type==='discipline'){if(n===0)return 10;return safe(n*(options.inClan?5:7))}if(type==='virtue'||type==='road')return safe(n*2);if(type==='willpower')return n;if(type==='path')return n===0?7:safe(n*4);if(type==='ritual')return safe(number(options.rating??n,'Nível do ritual',1,MAX,true)*2);if(type==='background'){if(!options.allowBackground)throw Error('Comprar Antecedentes com XP exige autorização do Narrador.');if(n===0)throw Error('O livro não define custo de XP para um Antecedente novo a partir de zero. Registre a concessão do Narrador pela edição da ficha.');return safe(n*2)}throw Error('Tipo de compra desconhecido.')}
function buyWithXP(c,options){if(c.creation.phase!=='play')throw Error('Comece a crônica antes de gastar experiência.');const {type,key}=options,trait=getTrait(c,type,key);const story=String(options.story||'').trim();if(!story)throw Error('Informe a história/capítulo desta compra para respeitar o limite de um aumento por característica em cada história.');if(c.experience.ledger.some(x=>x.type===type&&x.key===key&&x.story===story))throw Error('Esta característica já foi aumentada nesta história.');if(type==='ritual'&&trait.item.purchased)throw Error('Este ritual já foi aprendido.');const from=type==='ritual'?0:trait.rating,to=type==='ritual'?trait.rating:safe(from+1);if(c.rulesMode!=='free'&&to>trait.max)throw Error(`A compra elevaria ${trait.label} a ${to}, acima do limite ${trait.max}.`);const cost=experienceCost(type,from,{inClan:options.inClan??trait.inClan,caitiff:normalize(c.clan)==='caitiff',allowBackground:options.allowBackground,rating:trait.rating});if(cost<1)throw Error('Uma compra com custo zero exige uma decisão do Narrador; use edição livre e registre a justificativa.');const remaining=calculate(c).experienceRemaining;if(cost>remaining)throw Error(`Experiência insuficiente: a compra custa ${cost} XP e há ${remaining} disponíveis.`);const spent=safe(c.experience.spent+cost),record={id:uid(),type,key,label:trait.label,cost,from,to,story,notes:String(options.notes||''),at:new Date().toISOString()};trait.set(to);if(type==='ritual')trait.item.purchased=true;c.experience.spent=spent;c.experience.ledger.push(record);return record}
function addExperience(c,amount){const n=number(amount,'Experiência recebida',0,MAX,true);c.experience.total=safe(c.experience.total+n);return c.experience.total}
function startingBlood(c,rng=Math.random){const s=calculate(c),r=rng();if(!Number.isFinite(r)||r<0||r>=1)throw Error('Gerador de dados inválido.');const die=Math.floor(r*10)+1,herd=sum(c.backgrounds.filter(i=>['herd','rebanho'].includes(normalize(i.name))).map(i=>i.rating)),domain=sum(c.backgrounds.filter(i=>['domain','dominio'].includes(normalize(i.name))).map(i=>i.rating));const raw=safe(die+herd+domain),blood=s.bloodMax===null?raw:Math.min(s.bloodMax,raw);c.resources.blood=blood;return {die,herd,domain,blood,explanation:`1d10 (${die}) + Rebanho ${herd} + Domínio ${domain} = ${raw}; máximo de sangue ${s.bloodMax??'definido pelo Narrador'}; reserva inicial ${blood}.`}}
function text(v,label,max=100000){if(v==null)return '';if(typeof v!=='string'||v.length>max)throw Error(`${label}: texto inválido ou maior que ${max.toLocaleString('pt-BR')} caracteres. Nada foi cortado.`);return v}
function object(v,label){if(!v||typeof v!=='object'||Array.isArray(v))throw Error(label+': objeto inválido.');return v}
function array(v,label,max=1000){if(v==null)return [];if(!Array.isArray(v)||v.length>max)throw Error(label+': lista inválida ou extensa demais. Nada foi cortado.');return v}
function choice(v,allowed,fallback,label){if(v==null)return fallback;if(!allowed.includes(v))throw Error(label+': opção desconhecida.');return v}
function parseCharacter(raw,options={}){object(raw,'Ficha');const c=create();const preserve=!!options.preserveIds;c.id=preserve?text(raw.id||c.id,'Identificador',300):uid();for(const k of identityFields)c[k]=text(raw[k]??c[k],labels[k]||k,k==='portrait'?10*1024*1024:100000);if(c.portrait&&!/^data:image\/(png|jpeg|jpg|webp);base64,[A-Za-z0-9+/=]+$/.test(c.portrait))throw Error('Retrato inválido. Use uma imagem incorporada PNG, JPEG ou WebP.');c.generation=number(raw.generation??12,'Geração',3,MAX,true);c.rulesMode=choice(raw.rulesMode,['standard','free'],'standard','Modo de regras');for(const [field,keys] of [['attributes',attributes],['abilities',abilityKeys],['virtues',virtueKeys]]){if(raw[field]!=null)object(raw[field],field);for(const k of keys)c[field][k]=number(raw[field]?.[k]??c[field][k],labels[k],0,MAX,true)}
 const vt=raw.virtueTypes||{};c.virtueTypes={moral:choice(vt.moral,['conscience','conviction'],'conscience','Virtude moral'),restraint:choice(vt.restraint,['selfControl','instinct'],'selfControl','Virtude de controle')};c.roadScore=number(raw.roadScore??c.roadScore,'Caminho',0,MAX,true);c.willpower=number(raw.willpower??c.willpower,'Força de Vontade',0,MAX,true);if(raw.resources!=null)object(raw.resources,'Recursos');for(const k of ['blood','willpower'])c.resources[k]=number(raw.resources?.[k]??c.resources[k],labels[k],0,MAX,true);if(raw.health!=null)object(raw.health,'Vitalidade');for(const k of ['bashing','lethal','aggravated'])c.health[k]=number(raw.health?.[k]??0,'Dano',0,7,true);c.health.state=choice(raw.health?.state,['active','torpor','finalDeath'],'active','Estado vital');for(const k of ['traitLimit','bloodMax','bloodPerTurn'])c.campaign[k]=raw.campaign?.[k]==null?null:number(raw.campaign[k],k,0,MAX,true);
 c.specialties={};for(const [key,value] of Object.entries(object(raw.specialties||{},'Especialidades'))){if(![...attributes,...abilityKeys].includes(key))throw Error('Especialidade ligada a uma característica desconhecida.');c.specialties[key]=text(value,'Especialidade',2000)}c.conditions=array(raw.conditions,'Condições',100).map(v=>text(v,'Condição',2000));const idMap=new Map();const itemIds=new Set();
 for(const list of ['disciplines','backgrounds','paths','rituals','merits','flaws','inventory','bonuses'])c[list]=array(raw[list],list).map(r=>{object(r,list);const original=text(r.id||uid(),'Identificador da opção',300);if(itemIds.has(original))throw Error('Existem opções com identificadores repetidos.');itemIds.add(original);const id=preserve?original:uid();idMap.set(original,id);const i={id,name:text(r.name,'Nome',3000),notes:text(r.notes,'Notas'),book:text(r.book,'Livro',3000),page:r.page==null?0:number(r.page,'Página',0,MAX,true)};if(['disciplines','backgrounds','paths','rituals'].includes(list)){i.rating=number(r.rating??0,i.name,0,MAX,true);i.inClan=r.inClan!==false;i.granted=!!r.granted;if(r.purchased!=null)i.purchased=!!r.purchased;if(r.discipline!=null)i.discipline=text(r.discipline,'Disciplina da trilha',3000)}if(['merits','flaws'].includes(list))i.cost=number(r.cost??0,i.name,0,MAX,true);if(list==='inventory'){i.quantity=number(r.quantity??1,'Quantidade',0,MAX,true);i.equipped=!!r.equipped;i.weight=number(r.weight??0,'Peso',0,MAX);i.type=text(r.type,'Tipo',1000);i.damage=number(r.damage??0,'Modificador de dano',-MAX,MAX,true);i.armor=number(r.armor??0,'Armadura',0,MAX,true);i.penalty=number(r.penalty??0,'Penalidade de armadura',-MAX,MAX,true)}if(list==='bonuses'){i.target=choice(r.target,bonusTargets,'dice','Destino do modificador');i.value=number(r.value??0,'Modificador',-MAX,MAX,true);i.enabled=r.enabled!==false;i.duration=choice(r.duration,['permanent','scene','turns'],'permanent','Duração');i.remaining=number(r.remaining??0,'Turnos restantes',0,MAX,true)}return i});
 for(const list of ['journal','rolls'])c[list]=array(raw[list],list,list==='rolls'?1000:2000).map(r=>{if(typeof r==='string')return text(r,list);object(r,list);const allowed=list==='journal'?['id','title','text','at']:['id','label','explanation','outcome','at'];const item={};for(const k of allowed)if(r[k]!=null)item[k]=text(r[k],k);for(const k of ['pool','base','modifier','difficulty','ones','rawSuccesses','successes','automatic','healthPenalty','willpowerCost','die','total'])if(r[k]!=null)item[k]=number(r[k],k,-MAX,MAX,true);for(const k of ['botch','specialty'])if(r[k]!=null)item[k]=!!r[k];if(r.dice!=null)item.dice=array(r.dice,'Resultados',100000).map(n=>number(n,'Dado',1,10,true));return item});
 const cr=raw.creation||{};c.creation.phase=choice(cr.phase,['allocation','freebies','play'],'allocation','Etapa de criação');function priorities(v,keys,label){const a=array(v||keys,label,3);if(a.length!==3||new Set(a).size!==3||a.some(k=>!keys.includes(k)))throw Error(label+': escolha as três categorias uma única vez.');return [...a]}c.creation.attributePriorities=priorities(cr.attributePriorities,Object.keys(attributeGroups),'Prioridades de atributos');c.creation.abilityPriorities=priorities(cr.abilityPriorities,Object.keys(abilityGroups),'Prioridades de habilidades');c.creation.freebieBudget=number(cr.freebieBudget??15,'Pontos de bônus',0,MAX,true);c.creation.flawCreditLimit=number(cr.flawCreditLimit??7,'Crédito de defeitos',0,MAX,true);
 if(cr.base){object(cr.base,'Base de criação');const b=cr.base;c.creation.base={attributes:{},abilities:{},virtues:{},disciplines:[],backgrounds:[],paths:[],rituals:[],roadScore:number(b.roadScore,'Caminho inicial',0,MAX,true),willpower:number(b.willpower,'Força de Vontade inicial',0,MAX,true),clan:text(b.clan??c.clan,'Clã inicial',3000),attributePriorities:priorities(b.attributePriorities||c.creation.attributePriorities,Object.keys(attributeGroups),'Prioridades iniciais'),abilityPriorities:priorities(b.abilityPriorities||c.creation.abilityPriorities,Object.keys(abilityGroups),'Prioridades iniciais')};for(const [field,keys] of [['attributes',attributes],['abilities',abilityKeys],['virtues',virtueKeys]])for(const k of keys)c.creation.base[field][k]=number(b[field]?.[k],labels[k]+' inicial',0,MAX,true);for(const list of ['disciplines','backgrounds','paths','rituals'])c.creation.base[list]=array(b[list],'Base de '+list).map(i=>{object(i,'Opção inicial');const oldId=text(i.id,'Identificador inicial',300);const id=idMap.get(oldId)||(preserve?oldId:uid());idMap.set(oldId,id);return {id,name:text(i.name,'Nome inicial',3000),rating:number(i.rating,'Pontos iniciais',0,MAX,true),inClan:i.inClan!==false,granted:!!i.granted}})}
 const xp=raw.experience||{};c.experience.total=number(xp.total??0,'Experiência total',0,MAX,true);c.experience.spent=number(xp.spent??0,'Experiência gasta',0,MAX,true);c.experience.ledger=array(xp.ledger,'Compras de XP',2000).map(r=>{object(r,'Compra');const type=choice(r.type,traitTypes.map(t=>t.key),null,'Tipo de compra');if(!type)throw Error('Tipo de compra não informado.');let key=text(r.key,'Destino da compra',300);if(['discipline','background','path','ritual'].includes(type))key=idMap.get(key)||(preserve?key:uid());else if(type==='attribute'&&!attributes.includes(key)||type==='ability'&&!abilityKeys.includes(key)||type==='virtue'&&!virtueKeys.includes(key)||['road','willpower'].includes(type)&&key!==type)throw Error('Destino da compra de XP inválido.');return {id:preserve?text(r.id||uid(),'ID da compra',300):uid(),type,key,label:text(r.label,'Característica',3000),cost:number(r.cost,'Custo XP',0,MAX,true),from:number(r.from,'Valor anterior',0,MAX,true),to:number(r.to,'Valor atual',0,MAX,true),story:text(r.story,'História',3000),notes:text(r.notes,'Notas'),at:text(r.at,'Data',100)}});for(const k of ['createdAt','updatedAt'])c[k]=text(raw[k]||c[k],'Data',100);calculate(c);return c
}
function validateImport(raw,options={}){if(typeof raw==='string'){if(raw.length>100*1024*1024)throw Error('O arquivo excede 100 MB.');try{raw=JSON.parse(raw)}catch{throw Error('O arquivo não contém JSON válido.')}}let characters;if(Array.isArray(raw))characters=raw;else {object(raw,'Arquivo');if(raw.format&&raw.format!==FORMAT)throw Error('Este arquivo pertence a outro sistema de RPG.');if(raw.version!=null&&raw.version!==1)throw Error('Versão de ficha não suportada.');characters=raw.characters||[raw]}const list=array(characters,'Fichas',500);if(!list.length)throw Error('O arquivo não contém fichas.');const parsed=list.map(c=>parseCharacter(c,options));if(options.preserveIds&&new Set(parsed.map(c=>c.id)).size!==parsed.length)throw Error('Existem fichas com identificadores repetidos.');return parsed}
function pack(characters){return {format:FORMAT,version:1,exportedAt:new Date().toISOString(),characters}}
return {MAX,FORMAT,uid,number,normalize,attributes,attrs:attributes,attributeGroups,abilityGroups,abilityKeys,abilityDefinitions,groupLabels,labels,virtueKeys,traitTypes,bonusTargets,generationTable,freebieCosts,healthLevels,create,calculate,generationStats,setClan,setRoad,freezeCreation,enterPlay,spend,spendBlood:(c,n)=>spend(c,'blood',n),spendWillpower:(c,n)=>spend(c,'willpower',n),recover,roll,rollInitiative,applyDamage,heal,advanceTurn,endScene,startNight,experienceCost,buyWithXP,addExperience,startingBlood,validateImport,pack};
});
