const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
let main;
// Packaged desktop editions keep portable data beside their executable.
// An explicit profile path takes precedence for isolated runs and managed installs.
if(['win32','linux'].includes(process.platform)&&app.isPackaged&&!app.commandLine.hasSwitch('user-data-dir')){try{const data=path.join(path.dirname(process.execPath),'dados');fs.mkdirSync(data,{recursive:true});fs.accessSync(data,fs.constants.W_OK);app.setPath('userData',data)}catch{}}
app.setName('Sangue & Cinzas — Dark Ages V20');
const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();app.on('second-instance',()=>{if(main){if(main.isMinimized())main.restore();main.focus()}});
function trusted(e){if(e.sender!==main?.webContents)throw Error('Origem inválida')}
const datafile=()=>path.join(app.getPath('userData'),'fichas.json');
const Store=require('./store.cjs');let store;const getStore=()=>store||(store=new Store(datafile()));
ipcMain.handle('library',e=>{trusted(e);const f=path.join(__dirname,'data/library-local.json');if(!fs.existsSync(f))return null;const metadata=JSON.parse(fs.readFileSync(f,'utf8'));if(!fs.existsSync(path.join(__dirname,'data/catalog.js')))throw Error('Acervo local incompleto. Execute a importação novamente.');return metadata});
ipcMain.handle('load',e=>{trusted(e);return getStore().load()});
ipcMain.handle('save',(e,data)=>{trusted(e);return getStore().save(data)});
ipcMain.handle('export',async(e,{data,name})=>{trusted(e);const {canceled,filePath}=await dialog.showSaveDialog(main,{title:'Salvar ficha compartilhável',defaultPath:name.replace(/[<>:"/\\|?*]/g,'_')+'.dav20.json',filters:[{name:'Ficha Dark Ages V20',extensions:['json']}]});if(canceled)return false;fs.writeFileSync(filePath,JSON.stringify(data,null,2));return filePath});
ipcMain.handle('import',async e=>{trusted(e);const {canceled,filePaths}=await dialog.showOpenDialog(main,{title:'Importar ficha ou backup',filters:[{name:'Ficha Dark Ages V20',extensions:['json']}],properties:['openFile']});if(canceled)return null;if(fs.statSync(filePaths[0]).size>100*1024*1024)throw Error('Arquivo muito grande.');return JSON.parse(fs.readFileSync(filePaths[0],'utf8'))});
ipcMain.handle('pdf',async(e,html)=>{trusted(e);const {canceled,filePath}=await dialog.showSaveDialog(main,{defaultPath:'Ficha-Dark-Ages-V20.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(canceled)return false;const w=new BrowserWindow({show:false,webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));try{await w.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));const buf=await w.webContents.printToPDF({printBackground:true,pageSize:'A4',margins:{top:0.4,bottom:0.4,left:0.4,right:0.4}});fs.writeFileSync(filePath,buf);return filePath}finally{w.destroy()}});
ipcMain.handle('official',async(e,data)=>{trusted(e);if(!fs.existsSync(path.join(__dirname,'livros/ficha-oficial.pdf')))throw Error('Adicione seu PDF da ficha oficial ao acervo local conforme o README.');const {canceled,filePath}=await dialog.showSaveDialog(main,{title:'Salvar ficha oficial preenchida',defaultPath:'Ficha-DAV20-Oficial.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(canceled)return false;const bytes=await require('./official-form.cjs')(data);fs.writeFileSync(filePath,bytes);return filePath});
ipcMain.handle('source',async(e,{file,page})=>{trusted(e);const books=require('./data/books.json');if(!books.some(b=>b.file===file))throw Error('Livro desconhecido.');const f=path.join(__dirname,'livros',file);if(!fs.existsSync(f))throw Error('Adicione seus PDFs ao acervo local conforme o README do projeto.');const w=new BrowserWindow({width:1150,height:850,title:'Biblioteca • Sangue & Cinzas',webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',(ev,url)=>{if(!url.startsWith(pathToFileURL(f).href))ev.preventDefault()});await w.loadURL(pathToFileURL(f).href+'#page='+Math.max(1,Number(page)||1));return true});
app.whenReady().then(()=>{main=new BrowserWindow({width:1440,height:960,minWidth:900,minHeight:640,backgroundColor:'#101014',title:'Sangue & Cinzas — Dark Ages V20',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});main.webContents.setWindowOpenHandler(()=>({action:'deny'}));main.webContents.on('will-navigate',e=>e.preventDefault());main.loadFile(path.join(__dirname,'index.html'));let closing=false;main.on('close',event=>{if(closing)return;event.preventDefault();main.webContents.executeJavaScript('typeof flushSave === \'function\' ? flushSave() : null').catch(()=>{}).finally(()=>{closing=true;main.close()})});});
app.on('window-all-closed',()=>app.quit());
